spring.application.name=crudSpringBootDemo

spring.datasource.url = jdbc:mysql://localhost:3306/crud-spring-boot-demo
spring.datasource.username=root
spring.datasource.password=monu

spring.jpa.hibernate.ddl-auto=update
